version: '3.9'
services:
  cloudflare-ddns:
    image: docker.io/timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config.json:/config.json
    restart: unless-stopped
