---
## Command used to generate the secret:
## kubectl create secret generic cloudflare-api-token-secret \
## --namespace cert-manager \
## --dry-run=client \ 
## --output yaml \
## --from-literal=$TOKEN |\
## kubeseal --controller-name sealed-secrets --controller-namespace sealed-secrets \
## --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAhIHWQstTiJRNef5Sg1sKzwmSJuNnfAT8QVDjlxBvt31ZZv/pnpMaKmhKVLEVJY6FKvkDSyrqM0Mo1UuM2zPuuTrHH/Q3grW+rJ7zSCn+dWGM7gF0fXQUeRf2Lt0fziJyeM4VgADLo8rcdOpXnUIPlM6XMRFVBLSAfIRVlN4B4RWnFYefUJlPaDKn68QtCv9gf/2U0GQo9BJbaqODas2Z8SqkBlaVb5iCsw9b6St5bSHj3cgYt1XJQsjr9THeUo2HES/b/hYUx31HrkIluehOUcKsA3q/mzx/k45cJNmlisk+C3iQ6moF8mVpgiX5GA0zjR/8eo3qeWU2zvFCbMI0TkiQyB7VqsEsabhT5/eXoV4Zm6OhwsHwwU7WFBt1ds/3/qYf2cQODUfKALhXk2icdPjmixM5ySqWv6/E5pqxBY1Xl86ZTD5x2A+jga4MFv7yWEE5Bwl417akKCFla6sHbbQteF953+ogk7b3ISW6qwKTy2WvPY0pH+mb3835h00+a+nlxNkWuK6Pd7eCRtly0M4wO1HHJl+2Z5dI1VsUP9f6iNpWbKtKuJQCxkS2l1Wz+/LrC4B2SrR6OSmU/sMcNBml7U2Ea/A8cfYRMgjyAzxtfNiQFA6tu6IdKZZIRv/LSAvFq+eK+sVbOfGRBM9pSsgQiPhyIvrpE1+lSWsDOvVQMVWQ5m6ngl8iUxeUKtMs2PFlIRp+T0n1dLC8bxhougbcEgNA1YmOMDwFkRbkBkpYLJHanOUSJ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
