---
- name: Disable DNS stub listener
  ansible.builtin.shell: sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf

- name: Link netplan's resolve.conf
  ansible.builtin.shell: rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'

- name: Enable and restart haproxy service
  service:
    name: systemd-resolved
    state: restarted
    enabled: yes
