---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-cert-manager
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: Service
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: apps
    kind: Deployment
  - group: batch
    kind: Job
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  destinations:
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
    - 'https://charts.jetstack.io'
