---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-cert-manager
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: 'argoproj.io'
      kind: 'Application'
  destinations:
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
    - 'https://charts.jetstack.io'
