---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-traefik
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Ingress
  - group: ''
    kind: Service
  destinations:
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
