---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-cloudflare-ddns
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: apps
      kind: Deployment
  destinations:
    - namespace: 'cloudflare-ddns'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
