---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: appproject-longhorn
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.5.3
      helm:
        releaseName: longhorn
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/application-extras/longhorn/
      targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
