---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cloudflare-ddns
  namespace: argocd
spec:
  destination:
    namespace: cloudflare-ddns
    server: https://kubernetes.default.svc
  project: appproject-cloudflare-ddns
  source:
    repoURL: https://github.com/luckury/Homelab.git
    path: kubernetes/management/production/application-extras/cloudflare-ddns
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
