---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: appproject-metallb
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.13.12
      helm:
        releaseName: metallb
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/application/metallb/
      targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
