---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: appproject-cert-manager
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.1
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/application-extras/longhorn/
      targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
