---
- name: Setup (and prepare) Kubernetes nodes with extra software and configs
  hosts: cpn_nodes
  become: true
  vars:
    ansible_ssh_private_key_file: /root/.ssh/masterkey_homelab
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  tasks:
    - name: Configure nodes
      import_role:
        name: ../../ansible/kubernetes-common
#     - name: Deploy HAProxy and Keepalived
#       import_role:
#         name: ../../ansible/haproxy-keepalived
