---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: appproject-sealed-secrets
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.15.0
      helm:
        releaseName: sealed-secrets
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/application-extras/sealed-secrets/
      targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
