---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: homelab-extras
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: appproject-homelab
  sources:
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/ingresses
      targetRevision: main
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/namespaces
      targetRevision: main
    - repoURL: https://github.com/luckury/Homelab.git
      path: kubernetes/production/rbac-definitions
      targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
