---
## Command used to generate the secret:
## kubectl create secret generic foo --dry-run=client -o yaml --from-literal=api-token=<token> | kubeseal --controller-name sealed-secrets --controller-namespace sealed-secrets -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA/MkDpyFqQmicew48aHDj5lKCS7y4XYosWA4TgKnivF/B1ClH+OMygYaJj4ruwOg0WpgHU+qZQV5IrxV6bZlhNJE26E/Svo9WIpIJFztlIJiPCb+XFmsW+bHqlfUKyAU1IgVmBBDuGNutPHf1YxrI/y3ittaxI1a2KKmRlgG8dLrOvJaFmgpb/1pHb4Il4jv+LVLOKOInFRRXGF6beznC58UY6uLIuIO5DvG8+FhLhjlGJrZ6PIMLIszwGs7canNt18hB0d+QsfxQTpsCPmsqEkUKKw4FZKggJOjl1pvCMuYTorjMkRMAH+7BBNdylItoETdihX49vHvP8nHt5BoJq546Ct7sjBcw1jg1lh+B8egt6HW+udImd0z2WaPSGWNByOb3Pz4aeDJPyWjPtupCOp0qbcuNIRX1TXMgW6Oa7YFa/LxZQ1aeHt8xqiOz7ue9YlZrevKPdKo/Bmpkd4sDWx8hUu+DI+Y1kfi4wYcrGMz43KDcKIF5ZRVbXpsRbRPKztt+FFdxe8kWuRwL3GuaghKNAam9sSy4W4pVzyptng2KD6CEKEGaQP4OfmaOCoXdvmZSeG8Oi08U9sEnM+2iEeArFi6oQoQRRZotgJRW4EcIWkOny2YqScleSnTaWaGl/OQNQ6HOgTgUfOrLWGLZV/CePoqElNO1FPvLemf52qzkZPryFf3Hrv3rBcCAGHa/edwMMFGeXMhr3Rz6Ke2W6F2aWvX8gVZuqzKZUMN1BrVbd74Aaqkol
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
