---
# Source: https://docs.linuxserver.io/images/docker-netbootxyz/#microsoft-server-dhcp
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MENU_VERSION=2.0.47 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    volumes:
      - /path/to/config:/config
      - /path/to/assets:/assets #optional
    ports:
      - 3000:3000 # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80 # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
