---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-sealed-secrets
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: apps
      kind: Deployment
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
  destinations:
    - namespace: 'sealed-secrets'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
    - 'https://bitnami-labs.github.io/sealed-secrets'
