---
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: appproject-homelab
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
    - group: 'argoproj.io'
      kind: 'AppProject'
    - group: 'argoproj.io'
      kind: 'ApplicationSet'
    - group: 'argoproj.io'
      kind: 'Application'
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/luckury/Homelab'
